name: Publish dotnet core 3.1 (Restore with GPR)

on:
  push:
    branches: [master]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    env:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true
      DOTNET_NOLOGO: true
      GPR_READONLY_USER: ${{secrets.GPR_READONLY_USER}}
      GPR_READONLY_TOKEN: ${{secrets.GPR_READONLY_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
      - name: Add Github Package Registry source
        run: dotnet nuget add source -n github -u $GPR_READONLY_USER -p $GPR_READONLY_TOKEN --store-password-in-clear-text https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      - name: Restore dependencies
        run: dotnet restore
      # TODO: Uncomment if test setup has docker-compose dependencies
      # - name: Prepare test environment
      #   run: docker-compose up -d
      - name: Test
        run: dotnet test
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Pack
        run: dotnet pack -c Release

      - uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Push
        run: dotnet nuget push src/bin/Release/*.nupkg
