name: Publish dotnet core 3.1

on:
  push:
    branches: [ master ]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    env:
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
          source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      - name: Restore dependencies
        run: dotnet restore
      # TODO: Uncomment if test setup has docker-compose dependencies
      # - name: Prepare test environment
      #   run: docker-compose up -d
      - name: Test
        run: dotnet test
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Pack
        run: dotnet pack -c Release
      - name: Push
        run: dotnet nuget push src/bin/Release/*.nupkg